#!/usr/bin/env python3
"""
Cross-prompt (leave-one-prompt-out) evaluation.

Every prompt is evaluated against reference label rows while EXCLUDING the
rows that the prompt under evaluation generated itself. For the shipped
``silver_standard_crossval.jsonl`` (labels generated by v2, v3 and v6) this
means:

- v2, v3, v6 are scored only against labels from the OTHER two generators.
- v1, v4, v5 have no labels of their own in the file, so all rows are used.

Note the limits of this design, stated plainly:
- The reference labels are LLM-generated (gpt-4o-mini), i.e. silver labels.
  Metrics are agreement with that labeler, not accuracy vs. ground truth.
- Generator prompts still share a systematic bias with the tested prompts
  (same model family, same schema), so expect optimistic absolute numbers.

Requires an OpenAI API key. Use --dry-run for a no-API plumbing check
(metrics are not computed in dry-run mode).

Usage:
    python evaluate_crossval.py            # real run (API key required)
    python evaluate_crossval.py --dry-run  # offline plumbing check
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / 'src'))

from evaluation.evaluate_prompts import PromptEvaluator
from prompts.templates import ALL_PROMPTS


def evaluate_crossval(
    labels_path: str = 'data/labeled/silver_standard_crossval.jsonl',
    prompts_to_test: list = None,
    k_shot: int = 0,
    model: str = 'gpt-4o-mini',
    max_reviews: int = None,
    dry_run: bool = False,
    output_path: str = 'data/evaluation/experiment_crossval.json',
):
    """Evaluate prompts with leave-one-prompt-out label exclusion."""
    if prompts_to_test is None:
        prompts_to_test = list(ALL_PROMPTS.keys())

    print(f"\n{'=' * 70}")
    print("CROSS-PROMPT EVALUATION (LEAVE-ONE-PROMPT-OUT)")
    print(f"{'=' * 70}")
    print(f"Labels: {labels_path}")
    print(f"Testing: {prompts_to_test} (k_shot={k_shot})")
    print("Exclusion: each prompt is NOT scored against labels it generated")

    evaluator = PromptEvaluator(gold_standard_path=labels_path)
    if not evaluator.label_rows:
        print("\nNo reference labels found. Generate them first:")
        print("  python generate_crossval_labels.py --prompts v2 v3 v6 --samples N")
        return

    results = []
    for prompt_key in prompts_to_test:
        prompt = ALL_PROMPTS[prompt_key]
        own_rows = sum(
            1 for row in evaluator.label_rows
            if row.get('prompt_version', '').split('.')[0].lower() == prompt_key
        )
        print(f"\n{'─' * 70}")
        print(f"Testing {prompt_key} ({prompt.name}); "
              f"excluding {own_rows} self-generated label rows")

        try:
            result = evaluator.evaluate_prompt(
                prompt,
                dataset='validation',
                k_shot=k_shot,
                model=model,
                max_reviews=max_reviews,
                exclude_own_labels=True,
                dry_run=dry_run,
            )
            results.append(result)

            if not dry_run and 'error' not in (result.get('metrics') or {}):
                m = result['metrics']
                print(f"\nAgreement (label type: {result['label_source']['type']}):")
                print(f"  Theme F1: {m.get('theme_f1', 0):.2%}")
                print(f"  Sentiment exact: {m.get('sentiment_exact_agreement', 0):.2%}")
                print(f"  Risk agreement: {m.get('risk_agreement', 0):.2%}")
        except Exception as e:
            print(f"Error testing {prompt_key}: {type(e).__name__}: {e}")
            continue

    # Save results
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    summary = [{k: v for k, v in r.items() if k != 'predictions'} for r in results]
    payload = {
        'run_metadata': {
            'evaluation': 'leave-one-prompt-out cross-prompt agreement',
            'label_type': evaluator.label_type,
            'label_models': evaluator.label_models,
            'generator_prompts': evaluator.generator_prompts,
            'k_shot': k_shot,
            'model': model,
            'dry_run': dry_run,
            'timestamp_utc': datetime.now(timezone.utc).isoformat(),
            'note': ('Dry-run predictions are derived from the reference labels '
                     'and carry no performance meaning.' if dry_run else
                     'Metrics are agreement with LLM-generated silver labels, '
                     'not accuracy against human ground truth.'),
        },
        'results': summary,
    }
    with open(out, 'w') as f:
        json.dump(payload, f, indent=2)

    print(f"\n{'=' * 70}")
    print(f"RESULTS SAVED: {out}")
    print(f"{'=' * 70}")

    printable = [r for r in results if (r.get('metrics') or {}).get('theme_f1') is not None]
    if printable:
        print(f"\n{'Prompt':<12} {'Rows':>6} {'Reviews':>8} {'Theme F1':>10} "
              f"{'Sentiment':>10} {'Risk':>8}")
        print("-" * 60)
        for r in sorted(printable, key=lambda x: x['metrics']['theme_f1'], reverse=True):
            m = r['metrics']
            print(f"{r['prompt_version']:<12} {r['n_label_rows']:>6} "
                  f"{r['n_unique_reviews']:>8} {m['theme_f1']:>10.2%} "
                  f"{m['sentiment_exact_agreement']:>10.1%} "
                  f"{m['risk_agreement']:>8.1%}")
        print(f"\nLabel type: {evaluator.label_type} - these are agreement "
              f"numbers with a synthetic/LLM labeler, not accuracy.")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Leave-one-prompt-out cross-prompt evaluation")
    parser.add_argument('--labels', default='data/labeled/silver_standard_crossval.jsonl')
    parser.add_argument('--prompts', nargs='+', default=list(ALL_PROMPTS.keys()))
    parser.add_argument('--k-shot', type=int, default=0)
    parser.add_argument('--model', default='gpt-4o-mini')
    parser.add_argument('--max-reviews', type=int, default=None)
    parser.add_argument('--dry-run', action='store_true')
    parser.add_argument('--output', default='data/evaluation/experiment_crossval.json')
    args = parser.parse_args()

    evaluate_crossval(
        labels_path=args.labels,
        prompts_to_test=args.prompts,
        k_shot=args.k_shot,
        model=args.model,
        max_reviews=args.max_reviews,
        dry_run=args.dry_run,
        output_path=args.output,
    )
