#!/usr/bin/env python3
"""
Evaluate prompts with leakage-free cross-validation.

This ensures no prompt is tested against labels it generated itself.

Strategy:
- Generate labels using v2, v3, v6
- Test all prompts (including v5) against these labels
- This gives fair, unbiased estimates of performance

Usage:
    python evaluate_crossval.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent / 'src'))

from evaluation.evaluate_prompts import PromptEvaluator


def evaluate_crossval(
    labels_path: str = 'data/labeled/silver_standard_crossval.jsonl',
    prompts_to_test: list = None,
    output_path: str = 'data/evaluation/experiment_crossval.json'
):
    """
    Evaluate prompts using cross-validation labels.

    Args:
        labels_path: Path to cross-validation labels (generated by v2, v3, v6)
        prompts_to_test: List of prompt keys to test (default: all)
        output_path: Where to save results
    """

    if prompts_to_test is None:
        prompts_to_test = ['v1', 'v2', 'v3', 'v4', 'v5', 'v6']

    print(f"\n{'='*70}")
    print(f"CROSS-VALIDATION EVALUATION")
    print(f"{'='*70}")
    print(f"Labels from: v2, v3, v6 (NOT v5)")
    print(f"Testing: {prompts_to_test}")
    print(f"No leakage: ✓ (no prompt tested against its own labels)")

    # Initialize evaluator
    evaluator = PromptEvaluator(gold_standard_path=labels_path)

    if len(evaluator.gold_data) == 0:
        print("❌ No cross-validation labels found!")
        print(f"\nGenerate them first:")
        print(f"  python generate_crossval_labels.py --prompts v2 v3 v6 --samples 175")
        return

    print(f"\nDataset size: {len(evaluator.gold_data)}")

    results = []

    for prompt_key in prompts_to_test:
        print(f"\n{'─'*70}")
        print(f"Testing: {prompt_key}")
        print(f"{'─'*70}")

        try:
            from prompts.templates import get_prompt
            prompt = get_prompt(prompt_key)

            result = evaluator.evaluate_prompt(
                prompt,
                dataset='validation',
                k_shot=0,  # Test zero-shot for fair comparison
                model='gpt-4o-mini',
                dry_run=False
            )

            # Add metadata
            result['tested_against'] = ['v2', 'v3', 'v6']
            result['leakage_free'] = True

            results.append(result)

            # Print summary
            metrics = result['metrics']
            print(f"\nResults:")
            print(f"  Theme F1: {metrics.get('theme_f1', 0):.2%}")
            print(f"  Sentiment Acc: {metrics.get('sentiment_exact_accuracy', 0):.2%}")
            print(f"  Risk Acc: {metrics.get('risk_accuracy', 0):.2%}")

        except Exception as e:
            print(f"❌ Error testing {prompt_key}: {e}")
            continue

    # Save results
    output_path_obj = Path(output_path)
    output_path_obj.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path_obj, 'w') as f:
        json.dump(results, f, indent=2)

    print(f"\n{'='*70}")
    print(f"RESULTS SAVED: {output_path}")
    print(f"{'='*70}")

    # Print comparison table
    print(f"\n{'='*70}")
    print(f"CROSS-VALIDATION RESULTS COMPARISON")
    print(f"{'='*70}")

    print(f"\n{'Prompt':<15} {'Theme F1':<12} {'Sent Acc':<10} {'Risk Acc':<10}")
    print("-" * 47)

    for r in sorted(results, key=lambda x: x['metrics'].get('theme_f1', 0), reverse=True):
        metrics = r['metrics']
        print(f"{r['prompt_version']:<15} {metrics.get('theme_f1', 0):>10.2%} "
              f"{metrics.get('sentiment_exact_accuracy', 0):>9.1%} "
              f"{metrics.get('risk_accuracy', 0):>9.1%}")

    print(f"\n{'='*70}")
    print(f"✅ Cross-validation complete!")
    print(f"{'='*70}")


if __name__ == '__main__':
    evaluate_crossval()
